apiVersion: fsx.aws.upbound.io/v1beta1
kind: WindowsFileSystem
metadata:
  annotations:
    meta.upbound.io/example-id: fsx/v1beta1/windowsfilesystem
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    activeDirectoryId: ${aws_directory_service_directory.example.id}
    kmsKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    storageCapacity: 300
    subnetIdRefs:
    - name: example
    throughputCapacity: 1024

---

