apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: LifecycleHook
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta1/lifecyclehook
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    autoscalingGroupName: ${aws_autoscaling_group.foobar.name}
    defaultResult: CONTINUE
    heartbeatTimeout: 2000
    lifecycleTransition: autoscaling:EC2_INSTANCE_LAUNCHING
    notificationMetadata: |
      {
        "foo": "bar"
      }
    notificationTargetArn: arn:aws:sqs:us-east-1:444455556666:queue1*
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

