apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta1/policy
  labels:
    testing.upbound.io/example-name: bat
  name: bat
spec:
  forProvider:
    adjustmentType: ChangeInCapacity
    autoscalingGroupName: ${aws_autoscaling_group.bar.name}
    cooldown: 300
    region: us-west-1
    scalingAdjustment: 4

---

