apiVersion: autoscalingplans.aws.upbound.io/v1beta1
kind: ScalingPlan
metadata:
  annotations:
    meta.upbound.io/example-id: autoscalingplans/v1beta1/scalingplan
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationSource:
    - tagFilter:
      - key: application
        values:
        - example
    name: example-dynamic-cost-optimization
    region: us-west-1
    scalingInstruction:
    - maxCapacity: 3
      minCapacity: 0
      resourceId: ${format("autoScalingGroup/%s", aws_autoscaling_group.example.name)}
      scalableDimension: autoscaling:autoScalingGroup:DesiredCapacity
      serviceNamespace: autoscaling
      targetTrackingConfiguration:
      - predefinedScalingMetricSpecification:
        - predefinedScalingMetricType: ASGAverageCPUUtilization
        targetValue: 70

---

