apiVersion: sagemaker.aws.upbound.io/v1beta1
kind: Workteam
metadata:
  annotations:
    meta.upbound.io/example-id: sagemaker/v1beta1/workteam
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: example
    memberDefinition:
    - cognitoMemberDefinition:
      - clientId: ${aws_cognito_user_pool_client.example.id}
        userGroup: ${aws_cognito_user_group.example.id}
        userPool: ${aws_cognito_user_pool_domain.example.user_pool_id}
    region: us-west-1
    workforceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

