apiVersion: grafana.aws.upbound.io/v1beta1
kind: LicenseAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/licenseassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    licenseType: ENTERPRISE_FREE_TRIAL
    region: us-west-1
    workspaceId: ${aws_grafana_workspace.example.id}

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/licenseassociation
  labels:
    testing.upbound.io/example-name: assume
  name: assume
spec:
  forProvider:
    assumeRolePolicy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [
            {
              Action = "sts:AssumeRole"
              Effect = "Allow"
              Sid    = ""
              Principal = {
                Service = "grafana.amazonaws.com"
              }
            },
          ]
        })}

---

